[project]
name = "msc-cybersecurity-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.16.2",
    "polars>=1.33.1",
    "pytorch-lightning>=2.5.5",
    "scikit-learn>=1.7.2",
]
